### ISSUE TITLE
Slider and Drag functionality not working for Angular 9

### ISSUE THREAD

**Issue by vikas1vanvi** [A-l-y-l-e/Alyle-UI#113]
# :beetle: Bug report

### Describe the bug
Slider and Drag not working for Angular 9 , does this support Angular 9?

 
 
 

### Which versions of Angular, Alyle UI, OS, TypeScript, browsers are affected?

**Alyle UI Version:** 
`3.1.1`

**Angular Version:**
<pre><code>

Angular CLI: 9.0.5
Node: 12.14.1
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@angular/forms                    9.0.4
@angular/http                     7.2.16
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by Enlcxx** [comment]
Not yet supported for Angular 9, probably ready for early April.

**Comment by Enlcxx** [comment]
Fixed

**Comment by sankudey08** [comment]
**Alyle UI Version:**
3.0.0

**Angular Version:**

Angular CLI: 9.0.1
Node: 12.14.1
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material,  platform-browser,platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/language-service                    7.2.16
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.6.5
webpack                           4.41.2

**Comment:**
Draging is not working

**Comment by Enlcxx** [comment]
Install the latest version of Alyle UI, then add `HammerModule` & `LyHammerGestureConfig` to `AppModule`

https://alyle.io/getting-started/installation

**Comment by darita92** [comment]
this is still happening for me. Tried to add it on the `AppModule` as specified but still not working.

My project has multiple sub modules and tried a combination of adding on the Root module, submodule only and both and still no luck any ideas?

**Comment by Enlcxx** [comment]
@darita92 imported hammer js into your app? then did this? https://alyle.io/guides/lazy-loading. Adding it to the AppModule is enough.

**Comment by darita92** [comment]
hey @Enlcxx yes on my `package.json` I have

```
{
...
"hammerjs": "^2.0.8",
...
}
```

Then on my AppModule I add the references as specified on the docs. The actual component using the cropper in  my project is under a submodule that is imported on the AppModule does that influence?

**Comment by Enlcxx** [comment]
No, that doesn't matter. Open your project in the browser and in the console type `!!Hammer`, it should return `true`

**Comment by darita92** [comment]
Oh sorry I haven't worked with Hammer before, I saw that you need to add this to the `polyfill.ts` in angular

```
import 'hammerjs/hammer';
```

adding this resolved the issue, thanks!

**Comment by Enlcxx** [comment]
@darita92 you are welcome.

Use `import 'hammerjs';` instead of `import 'hammerjs/hammer';`.
